# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
      build:
        args:
          user: sammy
          uid: 1000
        context: ./
        dockerfile: Dockerfile
      image: app
      container_name: alice-app
      restart: unless-stopped
      volumes:
        - ./:/var/www
      networks:
        - sail
      depends_on:
        - postgresql
        - nginx
        - redis

    postgresql:
        image: postgres:13.1
        ports:
          - 5432:5432
        environment:
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_DB: '${DB_DATABASE}'
        volumes:
            - 'sailpsql:/var/lib/postgresql/data'
        networks:
            - sail
    redis:
        image: redis:alpine
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sailredis:/data'
        networks:
            - sail

    nginx:
      image: nginx:alpine
      container_name: app-nginx
      restart: unless-stopped
      ports:
        - 8000:80
      volumes:
        - ./:/var/www
        - ./storage/server:/etc/nginx/conf.d/
      networks:
        - sail

networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
    sailpsql:
        driver: local
